### PR TITLE
[MTOOLCHAINS-50] Update parent pom to 41

### PR DESCRIPTION
**Pull request by elharo**
JIRA issue: [MTOOLCHAINS-50](https://issues.apache.org/jira/browse/MTOOLCHAINS-50)

### CODE REVIEW

**Comment by elharo** [comment]
Nope. something seems off with the CI config:

Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.40.0:check failed: Unable to load the mojo 'check' in the plugin 'com.diffplug.spotless:spotless-maven-plugin:2.40.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/diffplug/spotless/maven/SpotlessCheckMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by gnodet** [comment]
> Nope. something seems off with the CI config:
> 
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.40.0:check failed: Unable to load the mojo 'check' in the plugin 'com.diffplug.spotless:spotless-maven-plugin:2.40.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/diffplug/spotless/maven/SpotlessCheckMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I think this requires JDK 17 at build time and should target JDK 8 at runtime.

**Comment by elharo** [comment]
55 is Java 11, I think

**Review by gnodet — APPROVED** [review]

**Comment by gnodet** [comment]
I'm merging this one as it blocks other PRs.

**Comment by jira-importer** [comment]
Resolve #109

**Pull request merged**
